// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.0
// source: product/app/v1/v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *RequestHead) Reset() {
	*x = RequestHead{}
	mi := &file_product_app_v1_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHead) ProtoMessage() {}

func (x *RequestHead) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHead.ProtoReflect.Descriptor instead.
func (*RequestHead) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHead) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ResponseHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq  uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResponseHead) Reset() {
	*x = ResponseHead{}
	mi := &file_product_app_v1_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHead) ProtoMessage() {}

func (x *ResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHead.ProtoReflect.Descriptor instead.
func (*ResponseHead) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHead) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ResponseHead) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *RequestHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Request_LoginWithOpenid
	//	*Request_LoginWithAccount
	Body isRequest_Body `protobuf_oneof:"body"`
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_product_app_v1_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetHead() *RequestHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (m *Request) GetBody() isRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Request) GetLoginWithOpenid() *LoginWithOpenIDRequest {
	if x, ok := x.GetBody().(*Request_LoginWithOpenid); ok {
		return x.LoginWithOpenid
	}
	return nil
}

func (x *Request) GetLoginWithAccount() *LoginWithAccountRequest {
	if x, ok := x.GetBody().(*Request_LoginWithAccount); ok {
		return x.LoginWithAccount
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_LoginWithOpenid struct {
	LoginWithOpenid *LoginWithOpenIDRequest `protobuf:"bytes,2,opt,name=login_with_openid,json=loginWithOpenid,proto3,oneof"`
}

type Request_LoginWithAccount struct {
	LoginWithAccount *LoginWithAccountRequest `protobuf:"bytes,3,opt,name=login_with_account,json=loginWithAccount,proto3,oneof"`
}

func (*Request_LoginWithOpenid) isRequest_Body() {}

func (*Request_LoginWithAccount) isRequest_Body() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ResponseHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Response_LoginWithOpenid
	//	*Response_LoginWithAccount
	Body isResponse_Body `protobuf_oneof:"body"`
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_product_app_v1_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetHead() *ResponseHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (m *Response) GetBody() isResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Response) GetLoginWithOpenid() *LoginWithOpenIDResponse {
	if x, ok := x.GetBody().(*Response_LoginWithOpenid); ok {
		return x.LoginWithOpenid
	}
	return nil
}

func (x *Response) GetLoginWithAccount() *LoginWithAccountResponse {
	if x, ok := x.GetBody().(*Response_LoginWithAccount); ok {
		return x.LoginWithAccount
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_LoginWithOpenid struct {
	LoginWithOpenid *LoginWithOpenIDResponse `protobuf:"bytes,2,opt,name=login_with_openid,json=loginWithOpenid,proto3,oneof"`
}

type Response_LoginWithAccount struct {
	LoginWithAccount *LoginWithAccountResponse `protobuf:"bytes,3,opt,name=login_with_account,json=loginWithAccount,proto3,oneof"`
}

func (*Response_LoginWithOpenid) isResponse_Body() {}

func (*Response_LoginWithAccount) isResponse_Body() {}

type LoginWithOpenIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginWithOpenIDRequest) Reset() {
	*x = LoginWithOpenIDRequest{}
	mi := &file_product_app_v1_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithOpenIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithOpenIDRequest) ProtoMessage() {}

func (x *LoginWithOpenIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithOpenIDRequest.ProtoReflect.Descriptor instead.
func (*LoginWithOpenIDRequest) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{4}
}

type LoginWithOpenIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginWithOpenIDResponse) Reset() {
	*x = LoginWithOpenIDResponse{}
	mi := &file_product_app_v1_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithOpenIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithOpenIDResponse) ProtoMessage() {}

func (x *LoginWithOpenIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithOpenIDResponse.ProtoReflect.Descriptor instead.
func (*LoginWithOpenIDResponse) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{5}
}

type LoginWithAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginWithAccountRequest) Reset() {
	*x = LoginWithAccountRequest{}
	mi := &file_product_app_v1_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithAccountRequest) ProtoMessage() {}

func (x *LoginWithAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithAccountRequest.ProtoReflect.Descriptor instead.
func (*LoginWithAccountRequest) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{6}
}

type LoginWithAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginWithAccountResponse) Reset() {
	*x = LoginWithAccountResponse{}
	mi := &file_product_app_v1_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithAccountResponse) ProtoMessage() {}

func (x *LoginWithAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_app_v1_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithAccountResponse.ProtoReflect.Descriptor instead.
func (*LoginWithAccountResponse) Descriptor() ([]byte, []int) {
	return file_product_app_v1_v1_proto_rawDescGZIP(), []int{7}
}

var File_product_app_v1_v1_proto protoreflect.FileDescriptor

var file_product_app_v1_v1_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31,
	0x2f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x34, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xf1, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x54, 0x0a,
	0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57,
	0x69, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x12, 0x57, 0x0a, 0x12, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0xf5, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x12, 0x55, 0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x58, 0x0a, 0x12, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x18, 0x0a, 0x16,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57,
	0x69, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x6e, 0x6a, 0x69, 0x61, 0x6e, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x2d, 0x61, 0x70, 0x69, 0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_product_app_v1_v1_proto_rawDescOnce sync.Once
	file_product_app_v1_v1_proto_rawDescData = file_product_app_v1_v1_proto_rawDesc
)

func file_product_app_v1_v1_proto_rawDescGZIP() []byte {
	file_product_app_v1_v1_proto_rawDescOnce.Do(func() {
		file_product_app_v1_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_app_v1_v1_proto_rawDescData)
	})
	return file_product_app_v1_v1_proto_rawDescData
}

var file_product_app_v1_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_app_v1_v1_proto_goTypes = []any{
	(*RequestHead)(nil),              // 0: product.app.v1.RequestHead
	(*ResponseHead)(nil),             // 1: product.app.v1.ResponseHead
	(*Request)(nil),                  // 2: product.app.v1.Request
	(*Response)(nil),                 // 3: product.app.v1.Response
	(*LoginWithOpenIDRequest)(nil),   // 4: product.app.v1.LoginWithOpenIDRequest
	(*LoginWithOpenIDResponse)(nil),  // 5: product.app.v1.LoginWithOpenIDResponse
	(*LoginWithAccountRequest)(nil),  // 6: product.app.v1.LoginWithAccountRequest
	(*LoginWithAccountResponse)(nil), // 7: product.app.v1.LoginWithAccountResponse
}
var file_product_app_v1_v1_proto_depIdxs = []int32{
	0, // 0: product.app.v1.Request.head:type_name -> product.app.v1.RequestHead
	4, // 1: product.app.v1.Request.login_with_openid:type_name -> product.app.v1.LoginWithOpenIDRequest
	6, // 2: product.app.v1.Request.login_with_account:type_name -> product.app.v1.LoginWithAccountRequest
	1, // 3: product.app.v1.Response.head:type_name -> product.app.v1.ResponseHead
	5, // 4: product.app.v1.Response.login_with_openid:type_name -> product.app.v1.LoginWithOpenIDResponse
	7, // 5: product.app.v1.Response.login_with_account:type_name -> product.app.v1.LoginWithAccountResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_product_app_v1_v1_proto_init() }
func file_product_app_v1_v1_proto_init() {
	if File_product_app_v1_v1_proto != nil {
		return
	}
	file_product_app_v1_v1_proto_msgTypes[2].OneofWrappers = []any{
		(*Request_LoginWithOpenid)(nil),
		(*Request_LoginWithAccount)(nil),
	}
	file_product_app_v1_v1_proto_msgTypes[3].OneofWrappers = []any{
		(*Response_LoginWithOpenid)(nil),
		(*Response_LoginWithAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_app_v1_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_app_v1_v1_proto_goTypes,
		DependencyIndexes: file_product_app_v1_v1_proto_depIdxs,
		MessageInfos:      file_product_app_v1_v1_proto_msgTypes,
	}.Build()
	File_product_app_v1_v1_proto = out.File
	file_product_app_v1_v1_proto_rawDesc = nil
	file_product_app_v1_v1_proto_goTypes = nil
	file_product_app_v1_v1_proto_depIdxs = nil
}
